### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by qinzhu** [xqwen/torus#1]
I'm trying to replicate the example in the tutorial, but ran into this error:

./torus -d geuv.summary.bf.gz --load_bf -smap geuv.snp.map.gz -gmap geuv.gene.map.gz -annot geuv.annot.gz  -est > geuv.enrichment.est
torus(597,0x7fffe8d843c0) malloc: *** error for object 0x7fff5b060000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

Suggestions would be appreciated.

**Comment by xqwen** [comment]
I tried to replicate the error with the current code in the repo but without success. A few things to check:
1. the downloaded data files are indeed in the required gzipped format. There were previous reports that some browsers automatically unzip the downloaded .gz files without changing the extensions.  If this is the case, rename the downloaded files by removing the ".gz" suffix and re-zip them.
2. If the problem persists, try to re-compile the code by turning off the "-O3" options in the Makefile.

Let me know if this helps.

**Comment by qinzhu** [comment]
Thanks for the reply. The problem still persists.
Previously I was using macOS 10.12 to compile the program. I suspect this might be a operating system issue and so I switched to a ubuntu 16.04 machine.
However, the program still runs into the "killed" error:

```
./torus -d geuv.summary.bf.gz --load_bf -smap geuv.snp.map.gz -gmap geuv.gene.map.gz -annot geuv.annot.gz  -est
Killed
```

I suspect it's due to the same memory leak issue. Is there any platform you recommend for torus? Also could this be due to some dependencies updated which break the program?

Thanks.

**Comment by xqwen** [comment]
The code is also compiled (and test run) on a ubuntu 16.04 box. Did the program provide any intermediate output to the stderr? I monitored a run of the example data, and it consumed a little bit more than 1G of memory, which I think is reasonable given the size of the data. 

Here are the version information of the required libraries
* gsl:  2.1
* blas: 3.6.0
* boost-iostreams: 1.58.0
---------------
And the following is the "g++ -v" output
```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
```
I'd suggest you extract a few thousand lines from the bayes factor file and run it again without -smap, -gmap and -annot options. Or, I can provide a smaller data set for you to test.

**Comment by qinzhu** [comment]
Thanks a lot for your quick reply! I increased the allocated RAM for the virtual machine and now it's running. I really appreciate your help.
