### ISSUE TITLE
Output columns for `--dump_pip`

### ISSUE THREAD

**Issue by jhchung** [xqwen/torus#4]
Hi,

I am trying to prepare my GWAS zscores for use with fastenloc and have a question about the output columns from `--dump_pip`. 

Is this the correct interpretation?
1. Variant ID
1. Locus ID
1. PIP
1. Prior

And the input for fastenloc would be the first three columns (variant ID, locus ID, PIP)?

I am using the current `torus.static` executable.

Thanks!

**Comment by xqwen** [comment]
Only the first 3 columns will be used by fastenloc. But you can directly use this output from torus: fastenloc will ignore any additional information other than the first 3 columns. 

Hope this helps,

William

**Comment by jhchung** [comment]
Thanks for the information. Closing the issue now.
