### ISSUE TITLE
ERROR: vector length n must be positive integer

### ISSUE THREAD

**Issue by cindywen96** [xqwen/torus#7]
Hi! I'm using the FastQTL mode with the following command
```
torus \
            -d {input.fastqtl} \
            --fastqtl \
            --est \
            --annot {input.annot} \
            > {output[0]} \
            &> {output[1]}
```
where fastqtl input is from FastQTL nominal mapping mode, columns are `loc_id, snp_id, dtss, nominal_pval, beta`
```
ENSG00000223972 rs61769339 650753 0.826556 0.0168068
ENSG00000223972 rs200188737 654380 0.987671 0.00459092
ENSG00000223972 rs12238997 681862 0.964344 0.00343177
```
annotation input,
```
SNP     TF_binding_site_d       promoter_flanking_region_d      promoter_d      open_chromatin_region_d enhancer_d
      CTCF_binding_site_d
rs61769339      0       1       0       0       0       0
rs200188737     0       1       0       0       0       0
```
I got error
```
gsl: init_source.c:29: ERROR: vector length n must be positive integer
Default GSL error handler invoked.
Aborted
```
What could be the cause?

Also, from code, function`load_data_fastqtl` requires the following columns: `loc_id, snp_id, dtss, pval, bhat, sdbeta`. However, FastQTL nominal mode does not output `sdbeta`. How could that be solved?

Thanks a lot,
Cindy

**Comment by RuochengDong** [comment]
Hi Cindy,
I met a similar error. Did you figure out how to fix this error? Thank you.
